#!/usr/bin/python
import sys
import io
import operator

# Create the new config file for writing
try:
    template = io.open(sys.argv[1] + '.tmpl', 'r')
    config = io.open(sys.argv[1] + '.tf','w')
except (IOError, IndexError) as e:
    print e
    print "Configuration template is required."
    sys.exit(1)

config.write(u'# This file is generated by tf-generator.py\n\n')
# Read the lines from the template, substitute the values, and write to the new config file
node_zone = {
    'etcd-a-01': "us-west-2a",
    'etcd-b-01': "us-west-2b",
    'etcd-c-01': "us-west-2c",
}

for node in sorted(node_zone):
    for line in io.open('etcd.tmpl', 'r'):
        if node in ('etcd-a-01'):
            if line.find("DEPENDS_ON") >=0:
                pass
            else: 
                line = line.replace('NAME', node)
                line = line.replace('ZONE', node_zone[node])
                line = line.replace('USERDATAFILE', 'cloud-config/etcd.yaml')
                config.write(line)
        else:
            line = line.replace('DEPENDS_ON', 'aws_instance.etcd-a-01' )
            line = line.replace('NAME', node)
            line = line.replace('ZONE', node_zone[node])
            line = line.replace('USERDATAFILE', 'cloud-config/etcd-join.yaml')
            config.write(line)
    config.write(u'\n')
            
print "Terratorm file " + sys.argv[1] + ".tf is generated. Run tfplay to test.\n"